Fixed mislabelled variable and parameter
1) Register endpoint was throwing the following error with valid payload:
AttributeError: 'User' object has no attribute 'id'.

This was due to the to_dict() function still referring to the wrong variable name. Updated to student_id.

2) Parameter name used to initialise algorithm_grade incorrect. Updated with correct parameter name.